### ISSUE TITLE
the code in void loop() does not get executed

### ISSUE THREAD

**Issue by rajbadri** [chriscook8/esp-arduino-apboot#1]
your sketch works perfectly. It connects to my wifi router and when i connect with the browser it gives "Hello from ESP8266". But when i try to code in the void loop() it does not get executed.

Please help

Thanks

**Comment by chriscook8** [comment]
That's mostly by design. The mdns1 function that contains the webserver url actions is set to loop. Since this is just a template for further use you would want to add your own actions to that section. One such action could be a return() to escape out of the webserver that is established in setup() and then to move on to the main loop() of the program or simply do your coding in this section.
